### ISSUE TITLE
update go-cose dependency

### ISSUE THREAD

**Issue by thomas-fossati** [veraison/psatoken#30]
Update go-cose dependency to [v1.0.0-alpha.1](https://github.com/veraison/go-cose/releases/tag/v1.0.0-alpha.1)

**Comment by yogeshbdeshpande** [comment]
Commit :
https://github.com/veraison/psatoken/commit/b93226b2297141571b20c40c514151843074b315

Resolves this..

**Comment by yogeshbdeshpande** [comment]
Closing this issue now!
